language: java
before_install:
- chmod +x gradlew
jdk:
- oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.gradle"
script:
- "./gradlew clean build"
notifications:
  slack:
    secure: BZT44vIv3GXGyGYBwb2Bo1zkY5YrpA7PcOBqkr4+0s2rsCNzFSeu/ZCLLqg2/BEKDEg3dcqSXk4Q46x8fJ3SLC0pfXhKZKVU/ubvNds01h6hnvsUXgewosHaYXzmCiHWB6cArfRotIR1ORnS03gJad2k1nA+//HFHPB/5a8fz58Pd8a357i542hZMnu83guwVE3jfxx8XHInIV397Jf0HRY0rudUbRFz365WVUJpZcwMZEwaNXAYh3H3voL2xMLde5hvIt6S40WFUDzOji5gm80/8dGT4cW4e6ywCbglkBWACR6jlObo6kURnK9C9dVWFCwPET2tb2yTg0vRwqNK/V/lugrmMmJHmMEqjzl48po4C/eTO0ihm+VHT9hcR1HQG9Ta9hWIq3m6qNCoT7QM9hQgglS4O1vVwtFMDSJ9z/PT+SqOTwr4rwbPn4CK9GAiUMe/XKXHxgIgBWb7UKZ6eY3OtdMkd/v4MJycZFUY1BUhGs5WGUqTZBh36spM8LktOQC8jCOdPwc4F6reX7WbfhZDDFWEgKfDRijqlBhDP0WTuZ05umNXUGHH0ONLijN82HBdb4+na8vg2eL1Pu+EIwfBgAKrhY2d9AyAU4KFIZNe6EeXqEVR7uywlO+TUAhC0gWjdTQrWyDNrIhnx7++8R867XcP89hX56BIBKdGkBc=
deploy:
  provider: heroku
  api_key:
    secure: oJ+eO1qGIma9VRFgmbLJEr/BcwGO83dSKpkwIwKXj0xZ1/siEowdlBeJcTRSkZJHnBCsuyfOcolqX+G0LdKsqzBhV4kvksIjDLYxX2gUdXlxPjqsc3trTSNIWhPsAjmpOXpm0OyheszwjTUbRUaoPFnWR0ShVKm4lJVbv87JLAJ3OOTNpT7jErLCo3FFcUNZZ8qhtCoIKYVijWW9a8JwIk9AIzZaJjdmi945I1GoAU6xDYvFeuacaI7VnaSpNXS9bYMbGWS7+iuI4cTU6GKhYBEIVIEytqT5HDWrDvM4BSDk1J4YMyyJmtAulX+pThPs51+ltvJ1n6ttr7LJyekgo7pqEY9EgerKUsjb1C/RJxVgqTMQUS5mRLeR8Yhoa+8XUYx81B7XHHrsz+pAjKPIPzPzjuOJZ+8QLoY9fLtJj54ExmzTbzbPAb00J8kJt/GjHb2Z72NbjPqIl4IcSbeU0lj6IJ8c+E8CqBc9cCfqsCuwLFM4cs2XHTyxTzqgsWcmkitwfLGtYH2rs4YyltmzdvPfy6ndBQfBeauPYVV7PfKFi665f286s+EY4OcqkoEr+kqmc5LJo/ph1GcVutWDngI1TAjV8+r4JaZr1qXp1L1LkklUZ5jqL86majNJYuSmySDafHgHrX8RdZQB6b+Q2jkmiOrTE9qBow+v5xmpfjo=
  app: myrapo
