language: java
before_install:
- chmod +x gradlew
jdk:
- oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.gradle"
script:
- "./gradlew clean build"
notifications:
  slack:
    secure: BZT44vIv3GXGyGYBwb2Bo1zkY5YrpA7PcOBqkr4+0s2rsCNzFSeu/ZCLLqg2/BEKDEg3dcqSXk4Q46x8fJ3SLC0pfXhKZKVU/ubvNds01h6hnvsUXgewosHaYXzmCiHWB6cArfRotIR1ORnS03gJad2k1nA+//HFHPB/5a8fz58Pd8a357i542hZMnu83guwVE3jfxx8XHInIV397Jf0HRY0rudUbRFz365WVUJpZcwMZEwaNXAYh3H3voL2xMLde5hvIt6S40WFUDzOji5gm80/8dGT4cW4e6ywCbglkBWACR6jlObo6kURnK9C9dVWFCwPET2tb2yTg0vRwqNK/V/lugrmMmJHmMEqjzl48po4C/eTO0ihm+VHT9hcR1HQG9Ta9hWIq3m6qNCoT7QM9hQgglS4O1vVwtFMDSJ9z/PT+SqOTwr4rwbPn4CK9GAiUMe/XKXHxgIgBWb7UKZ6eY3OtdMkd/v4MJycZFUY1BUhGs5WGUqTZBh36spM8LktOQC8jCOdPwc4F6reX7WbfhZDDFWEgKfDRijqlBhDP0WTuZ05umNXUGHH0ONLijN82HBdb4+na8vg2eL1Pu+EIwfBgAKrhY2d9AyAU4KFIZNe6EeXqEVR7uywlO+TUAhC0gWjdTQrWyDNrIhnx7++8R867XcP89hX56BIBKdGkBc=

deploy:
  provider: heroku
  api_key: 832f55f8-4dc7-4d1f-9b33-3ccaace1d152
  app: myrapo

